$(document).ready(function() {
    $('#ratyRating').raty({
        path: '/vendor/raty/img',
        size: 24,
        // The name of hidden field generated by Raty
        scoreName: 'star',
        // Revalidate the star rating whenever user change it
        click: function (score, evt) {
            $('#ratyForm').bootstrapValidator('revalidateField', 'star');
        }
    });

    $('#ratyForm').bootstrapValidator({
        // The disabled elements are excluded
        // Hidden elements (including the rating star) are included
        excluded: ':disabled',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            star: {
                validators: {
                    notEmpty: {
                        message: 'The rating is required'
                    }
                }
            },
            title: {
                validators: {
                    notEmpty: {
                        message: 'The review title is required'
                    }
                }
            },
            content: {
                validators: {
                    notEmpty: {
                        message: 'The review content is required'
                    },
                    stringLength: {
                        max: 200,
                        message: 'The review content must be less than 200 characters'
                    }
                }
            }
        }
    });
});